### ISSUE TITLE
Documentation is missing python version setup

### ISSUE THREAD

**Issue by tdaede** [keirf/Greaseweazle#125]
If running ./scripts/setup.sh, as the wiki suggests, the version module is not built:

```
Traceback (most recent call last):
  File "/home/thomas/sandbox/Greaseweazle/./gw", line 11, in <module>
    import gw
  File "/home/thomas/sandbox/Greaseweazle/scripts/gw.py", line 15, in <module>
    from greaseweazle import version
```

Running `make pysetup` does do it correctly, and the instructions on the wiki should probably replace the ./scripts/setup.sh instruction with that.

**Comment by keirf** [comment]
If you download a release tarball then the `version.py` file is included.
